language: node_js
node_js:
  - "0.10"
services:
  - mongodb
  - redis-server
notifications:
  email: false
script:
  - npm run syntax
  - npm test
after_script:
  - npm run coveralls
env:
  global:
    - DEBUG= 1
    - secure: "FLX9eTJVNwkDH9uvxIEuaLA0NG5yZcpXycUvqJkUyQBcZRs4CY+OUzygqXBStICNOoAFQgCMKfCJ8VCgLV92Nyl/35JD5iO/aUcJ2zJ83NSqJTwk4hMan4YUTmYX2zNfJ6kU9P21Q1BJ/f9nQtOXmI1gC4X8uN39ms/iWfMI8kI="
    - secure: "TlFEgk6iZChRcIu0gv1VIgkapTsjF5UvL+/b2WNFKvACjY/Ls5UBZg46+Tj4MnbURrqGcWiwSGlro0U1ru3lgLyeV/dNEym281y/UWUt6AsRQofCd0pgCvgj/R13p2WFXYFx6AycQpbVp3tdwy9+5iSmB2RRAi1oAto4fqafwoU="
    - secure: "IOrV4h+GuA8xzowpawBXGNmweI2QSqmMs3xRJ07zENJLIE6deMRCFgLmF+uNphD7kmeWAAWV7gCLqL0mrl2t2oj3KQwdx4QogcjzQDe1qr9jBQyLpEgaAjlRGhUSu/crTsBwnfs7yMIsoXWO6tmBsiiVeV9nqqWvirUfUjIntpE="
